/**
 * Tajweed Challenge - Question Bank
 * Prepared by Sheikh Gehad Elsayad
 */

(function(window) {
    "use strict";

    const E = [
        "Two identical letters with the same exit point and characteristics meet → Identical Letters (Mutamathilayn).",
        "Two letters sharing the same exit point but differing in characteristics meet → Similar Letters (Mutajanisayn).",
        "Two letters close in exit point and characteristics meet → Close Letters (Mutaqaribayn).",
        "Hamzah precedes the Madd letter in the same word without a following Hamzah or Sukoon → Substitute Madd (Madd Badal, 2 counts).",
        "Madd letter followed by a Hamzah in the SAME word → Obligatory Connected Madd (Madd Wajib Muttasil, 4-5 counts).",
        "Madd letter at the end of a word followed by a Hamzah at the start of the next word → Permissible Separated Madd (Madd Ja'iz Munfasil, 4-5 counts).",
        "Stopping on Tanween Fath (ً) replaced with a prolonged Alif of 2 counts → Compensatory Madd (Madd 'Iwad, 2 counts).",
        "Meeting of two Yaas (the first with Shaddah & Kasrah and the second Saakinah) → Stabilizing Madd (Madd At-Tamkeen, 2 counts).",
        "Ha of pronoun (هاء الضمير) between two voweled letters not followed by Hamzah → Minor Connecting Madd (Madd Silah Sughra, 2 counts when continuing).",
        "Ha of pronoun (هاء الضمير) between two voweled letters followed by a Hamzah → Major Connecting Madd (Madd Silah Kubra, 4-5 counts when continuing).",
        "Madd letter followed by a letter that receives an incidental Sukoon due to stopping → Temporary Madd (Madd 'Aarid Li-Sukoon, 2, 4, or 6 counts).",
        "Leen letter (Waw or Yaa Saakinah preceded by Fathah) followed by an incidental Sukoon due to stopping → Soft Madd (Madd Al-Leen, 2, 4, or 6 counts).",
        "Madd letter (Alif, Waw, or Yaa) with no Hamzah or Sukoon before or after it → Natural Madd (Madd Tabee'ee, 2 counts).",
        "Madd letter followed by an original Sukoon merged into Shaddah in the same word → Compulsory Word-Based Heavy (Madd Lazim Kalimi Muthaqqal, 6 counts).",
        "Madd letter followed by an unmerged original Sukoon (without Shaddah) in the same word → Compulsory Word-Based Light (Madd Lazim Kalimi Mukhaffaf, 6 counts, e.g. ءَآلْـَٰٔنَ).",
        "Letter Lām (لاَمْ) is spelled with 3 letters whose middle is Madd and ending Saakin Meem is merged (Idgham) into the following Meem → Compulsory Letter-Based Heavy (Madd Lazim Harfi Muthaqqal, 6 counts).",
        "Letter Meem (مِيمْ) is spelled with 3 letters whose middle is Madd and ending Saakin Meem is NOT merged (no Idgham) → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).",
        "Letter Sād (صَادْ) is spelled with 3 letters whose middle is Madd and ending Saakin Daal is pronounced with Qalqalah (no Idgham) → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).",
        "Letter Seen (سِينْ) is spelled with 3 letters whose middle is Madd and ending Saakin Noon is NOT merged with Idgham → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).",
        "Letter Qāf (قَافْ) is spelled with 3 letters whose middle is Madd and ending Saakin Faa is NOT merged (no Idgham) → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).",
        "The word contains a Qalqalah letter (ق، ط، ب، ج، د) with Sukoon → The sound bounces.",
        "Qalqalah letter with Sukoon in the middle of a word → Minor Qalqalah (Qalqalah Sughra).",
        "Stopping on an unvoweled Qalqalah letter without Shaddah at the end of the word → Medium Qalqalah (Qalqalah Wusta).",
        "Stopping on a doubled (mushaddad) Qalqalah letter at the end of the word → Major Qalqalah (Qalqalah Kubra).",
        "Noon Sakinah followed by Yaa in the same word.",
        "Noon Sakinah followed by Waw in the same word.",
        "Noon Sakinah or Tanween followed by an Ikhfa letter → Hiding with Ghunnah (Ikhfa Haqiqi).",
        "Noon Sakinah or Tanween followed by one of (ي، ن، م، و) → Merging with Ghunnah (Idgham bi-Ghunnah).",
        "Noon Sakinah or Tanween followed by (ل، ر) → Merging without Ghunnah (Idgham bi-Ghayr Ghunnah).",
        "Noon Sakinah or Tanween followed by a throat letter (ء، هـ، ع، ح، غ، خ) → Clear pronunciation (Izhar).",
        "Noon Sakinah or Tanween followed by Baa (ب) → Changed to Meem with Ghunnah (Iqlab).",
        "The Ghunnah of Ikhfa is Heavy (Tafkheem) because it is followed by a heavy letter (ص، ض، ط، ظ، ق).",
        "The Ghunnah of Ikhfa is Light (Tarqeeq) because it is followed by a light letter.",
        "Incomplete Idgham (Naqis): The Noon or Tanween merges into (و / ي) while preserving its nasal Ghunnah sound, so there is no Shaddah.",
        "Complete Idgham (Kamil): The Noon or Tanween completely merges into the nasal letter (م / ن), receiving a Shaddah.",
        "Complete Idgham (Kamil): The Noon or Tanween and its Ghunnah completely disappear into (ل / ر), receiving a Shaddah.",
        "Meem Sakinah followed by a letter other than Baa or Meem → Oral Clarity (Izhar Shafawi).",
        "Meem Sakinah followed by Meem (م) → Two identical letters merge together (Idgham Shafawi).",
        "Meem Sakinah followed by Baa (ب) → Oral Hiding (Ikhfa Shafawi).",
        "This is the most complete ghunna.",
        "Raa with Kasrah (or Saakinah preceded by Kasrah or Yaa) → Light Raa (Muraqqaqah).",
        "The letter is one of the Isti'la letters (خص ضغط قظ) → Always Heavy.",
        "Alif preceded by a light letter → Light Alif.",
        "Alif preceded by a heavy letter → Heavy Alif.",
        "Raa with Fathah or Dammah (or Saakinah preceded by Fathah/Dammah) → Heavy Raa (Mufakhkhamah).",
        "Raa with Sukoon when stopping preceded by Kasrah → Both permissible, Light (Tarqeeq) is preferred.",
        "Lam in \"Allah\" preceded by Fathah or Dammah → Heavy Lam (Tafkheem).",
        "Lam in \"Allah\" preceded by Kasrah → Light Lam (Tarqeeq).",
        "Hamzat Al-Wasl occurs in connected speech → Dropped in pronunciation (Saqitah Waslan).",
        "Third letter of the verb has an original Dammah → Start with Dammah.",
        "Hamzat Al-Wasl in the definite article \"Al\" (ال) → Start with Fathah.",
        "Third letter of the verb has a Fathah or Kasrah, or in specified nouns → Start with Kasrah.",
        "Lam followed by a Lunar letter (from ابغ حجك وخف عقيمه) → Clearly pronounced Lam (Lam Qamariyyah).",
        "Lam followed by a Solar letter with Shaddah → Merged Lam (Lam Shamsiyyah).",
        "The Lam of \"Bal\" merges completely into the following letter Raa (Idgham).",
        "The Lam of \"Bal\" merges into the identical letter Laam (Idgham Mutamathilayn).",
        "The Lam of \"Hal\" merges into the identical letter Laam (Idgham Mutamathilayn)."
    ];

    function q(id, ans, exp, subcat, src, choices, prompt) {
        const item = {
            id: id,
            src: src || ("images/" + id + ".png"),
            ans: ans,
            explanation: typeof exp === "number" ? E[exp] : exp
        };
        if (prompt) item.prompt = prompt;
        if (subcat) item.subcat = subcat;
        if (choices) item.choicesList = choices;
        return item;
    }

    function defCat(title, choices, defaultPrompt, questions) {
        return {
            title: title,
            choices: choices,
            questions: questions.map(function(item) {
                if (!item.prompt && defaultPrompt) item.prompt = defaultPrompt;
                return item;
            })
        };
    }

    const TAJWEED_BANK = {
        "letter_relations": defCat("Letter Relationships", ["Identical","Similar","Close"], "What's the relation between these two letters?", [
            q("mutamathilayn_Screenshot_1", "Identical", 0),
            q("mutamathilayn_Screenshot_10", "Identical", 0),
            q("mutamathilayn_Screenshot_11", "Identical", 0),
            q("mutamathilayn_Screenshot_12", "Identical", 0),
            q("mutamathilayn_Screenshot_13", "Identical", 0),
            q("mutamathilayn_Screenshot_14", "Identical", 0),
            q("mutamathilayn_Screenshot_15", "Identical", 0),
            q("mutamathilayn_Screenshot_16", "Identical", 0),
            q("mutamathilayn_Screenshot_2", "Identical", 0),
            q("mutamathilayn_Screenshot_3", "Identical", 0),
            q("mutamathilayn_Screenshot_4", "Identical", 0),
            q("mutamathilayn_Screenshot_5", "Identical", 0),
            q("mutamathilayn_Screenshot_6", "Identical", 0),
            q("mutamathilayn_Screenshot_7", "Identical", 0),
            q("mutamathilayn_Screenshot_8", "Identical", 0),
            q("mutamathilayn_Screenshot_9", "Identical", 0),
            q("mutajanisayn_Screenshot_1", "Similar", 1),
            q("mutajanisayn_Screenshot_17", "Similar", 1),
            q("mutajanisayn_Screenshot_2", "Similar", 1),
            q("mutajanisayn_Screenshot_3", "Similar", 1),
            q("mutajanisayn_Screenshot_4", "Similar", 1),
            q("mutajanisayn_Screenshot_5", "Similar", 1),
            q("mutajanisayn_Screenshot_6", "Similar", 1),
            q("mutajanisayn_Screenshot_7", "Similar", 1),
            q("mutajanisayn_Screenshot_8", "Similar", 1),
            q("mutajanisayn_Screenshot_9", "Similar", 1),
            q("mutaqaribayn_Screenshot_1", "Close", 2),
            q("mutaqaribayn_Screenshot_10", "Close", 2),
            q("mutaqaribayn_Screenshot_2", "Close", 2),
            q("mutaqaribayn_Screenshot_3", "Close", 2),
            q("mutaqaribayn_Screenshot_4", "Close", 2),
            q("mutaqaribayn_Screenshot_5", "Close", 2)
        ]),
        "madd_rules": defCat("Madd Rules", ["Natural Madd","Substitute","Connected","Separated","Compensatory Madd","Stabilizing Madd","Minor Sila Madd","Major Sila Madd","Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light","Temporary Madd","Soft Madd"], "What is the Madd rule?", [
            q("madd_e0fe74f9", "Substitute", 3, null, "images/img_0125.png"),
            q("madd_be57cf7a", "Substitute", 3, null, "images/img_0126.png"),
            q("madd_7dfbfc8f", "Substitute", 3, null, "images/img_0127.png"),
            q("madd_0617e0c1", "Substitute", 3, null, "images/img_0128.png"),
            q("madd_b53310de", "Substitute", 3, null, "images/img_0129.png"),
            q("madd_f80e9891", "Substitute", 3, null, "images/img_0130.png"),
            q("madd_0fb417b6", "Substitute", 3, null, "images/img_0131.png"),
            q("madd_7eb0bdb6", "Substitute", 3, null, "images/img_0132.png"),
            q("madd_5d5f2214", "Substitute", 3, null, "images/img_0133.png"),
            q("madd_afce5309", "Substitute", 3, null, "images/img_0134.png"),
            q("madd_7158949c", "Substitute", 3, null, "images/img_0135.png"),
            q("madd_e2c114bc", "Substitute", 3, null, "images/img_0136.png"),
            q("madd_1bb653cd", "Substitute", 3, null, "images/img_0137.png"),
            q("madd_d8f9eb5a", "Substitute", 3, null, "images/img_0138.png"),
            q("madd_f6682a59", "Substitute", 3, null, "images/img_0139.png"),
            q("madd_0c5ce45c", "Substitute", 3, null, "images/img_0140.png"),
            q("madd_4671ed78", "Substitute", 3, null, "images/img_0141.png"),
            q("madd_348e55d2", "Connected", 4, null, "images/img_0142.png"),
            q("madd_db46d8a9", "Connected", 4, null, "images/img_0143.png"),
            q("madd_2a7c7e81", "Connected", 4, null, "images/img_0144.png"),
            q("madd_370f2d2b", "Connected", 4, null, "images/img_0145.png"),
            q("madd_402b670b", "Connected", 4, null, "images/img_0146.png"),
            q("madd_1f61053e", "Connected", 4, null, "images/img_0147.png"),
            q("madd_c2c26fd6", "Connected", 4, null, "images/img_0148.png"),
            q("madd_411e9547", "Connected", 4, null, "images/img_0149.png"),
            q("madd_cc9a9386", "Connected", 4, null, "images/img_0150.png"),
            q("madd_d6e980d1", "Connected", 4, null, "images/img_0151.png"),
            q("madd_ced99ac0", "Connected", 4, null, "images/img_0152.png"),
            q("madd_46692fa2", "Connected", 4, null, "images/img_0153.png"),
            q("madd_9f6c1c12", "Connected", 4, null, "images/img_0154.png"),
            q("madd_0c29e2a7", "Connected", 4, null, "images/img_0155.png"),
            q("madd_0e49400d", "Connected", 4, null, "images/img_0156.png"),
            q("madd_b5e4ec44", "Connected", 4, null, "images/img_0157.png"),
            q("madd_686f510e", "Separated", 5, null, "images/img_0158.png"),
            q("madd_a9891e84", "Separated", 5, null, "images/img_0159.png"),
            q("madd_1dedb84e", "Separated", 5, null, "images/img_0160.png"),
            q("madd_6bd0de7a", "Separated", 5, null, "images/img_0161.png"),
            q("madd_2839b2db", "Separated", 5, null, "images/img_0162.png"),
            q("madd_f31697f0", "Separated", 5, null, "images/img_0163.png"),
            q("madd_def577bd", "Separated", 5, null, "images/img_0164.png"),
            q("madd_71b7a4a4", "Separated", 5, null, "images/img_0165.png"),
            q("madd_badf7903", "Separated", 5, null, "images/img_0166.png"),
            q("madd_65d70fb5", "Separated", 5, null, "images/img_0167.png"),
            q("madd_6ea8ca18", "Separated", 5, null, "images/img_0168.png"),
            q("madd_ad485454", "Separated", 5, null, "images/img_0169.png"),
            q("madd_8ec133ee", "Separated", 5, null, "images/img_0170.png"),
            q("madd2_ba4d817f", "Compensatory Madd", 6, null, "images/img_0171.png"),
            q("madd2_a6c4aaf3", "Compensatory Madd", 6, null, "images/img_0172.png"),
            q("madd2_53a9372e", "Compensatory Madd", 6, null, "images/img_0173.png"),
            q("madd2_cac2a397", "Compensatory Madd", 6, null, "images/img_0174.png"),
            q("madd2_869bda31", "Compensatory Madd", 6, null, "images/img_0175.png"),
            q("madd2_8d902d51", "Compensatory Madd", 6, null, "images/img_0176.png"),
            q("madd2_5071ca4a", "Compensatory Madd", 6, null, "images/img_0177.png"),
            q("madd2_75bb5c25", "Compensatory Madd", 6, null, "images/img_0178.png"),
            q("madd2_deee274e", "Compensatory Madd", 6, null, "images/img_0179.png"),
            q("madd2_33081a7d", "Compensatory Madd", 6, null, "images/img_0180.png"),
            q("madd2_7e28d5a3", "Compensatory Madd", 6, null, "images/img_0181.png"),
            q("madd2_26fec3f0", "Compensatory Madd", 6, null, "images/img_0182.png"),
            q("madd2_5fe18aaa", "Compensatory Madd", 6, null, "images/img_0183.png"),
            q("madd2_8cb076f2", "Compensatory Madd", 6, null, "images/img_0184.png"),
            q("madd2_d1a1896c", "Compensatory Madd", 6, null, "images/img_0185.png"),
            q("madd2_a8d454ae", "Compensatory Madd", 6, null, "images/img_0186.png"),
            q("madd2_9c2b91e2", "Compensatory Madd", 6, null, "images/img_0187.png"),
            q("madd2_9ce50fc0", "Stabilizing Madd", 7, null, "images/img_0188.png"),
            q("madd2_7d03507a", "Stabilizing Madd", 7, null, "images/img_0189.png"),
            q("madd2_6b849779", "Stabilizing Madd", 7, null, "images/img_0190.png"),
            q("madd2_3ff90603", "Stabilizing Madd", 7, null, "images/img_0191.png"),
            q("madd_tamkeen_ummiyyeen", "Stabilizing Madd", "Meeting of two Yaas in one word (the first with Shaddah & Kasrah, and the second Saakinah) → Stabilizing Madd (Madd At-Tamkeen, 2 counts).", "Stabilizing Madd"),
            q("madd_tamkeen_allathee_yuwaswis", "Stabilizing Madd", "Meeting of a Madd Yaa at the end of a word followed by a voweled Yaa at the start of the next word → Stabilizing Madd (Madd At-Tamkeen, 2 counts to prevent merging/dropping).", "Stabilizing Madd"),
            q("madd_tamkeen_yalwoona", "Stabilizing Madd", "Meeting of two Waws in one word (the first with Dammah and the second Saakinah Madd Waw) → Stabilizing Madd (Madd At-Tamkeen, 2 counts).", "Stabilizing Madd"),
            q("madd_tamkeen_aamanoo_wa_amiloo", "Stabilizing Madd", "Meeting of a Madd Waw at the end of a word followed by a voweled Waw at the start of the next word → Stabilizing Madd (Madd At-Tamkeen, 2 counts to prevent merging/dropping).", "Stabilizing Madd"),
            q("madd2_a6585f14", "Minor Sila Madd", 8, null, "images/img_0192.png"),
            q("madd2_5c33a8dd", "Minor Sila Madd", 8, null, "images/img_0193.png"),
            q("madd2_a3d30699", "Minor Sila Madd", 8, null, "images/img_0194.png"),
            q("madd2_a4ddd054", "Minor Sila Madd", 8, null, "images/img_0195.png"),
            q("madd2_7e9d5db2", "Minor Sila Madd", 8, null, "images/img_0196.png"),
            q("madd2_79346fc0", "Minor Sila Madd", 8, null, "images/img_0197.png"),
            q("madd2_2069fa82", "Minor Sila Madd", 8, null, "images/img_0198.png"),
            q("madd2_2d493657", "Major Sila Madd", 9, null, "images/img_0199.png"),
            q("madd2_ca6c29bc", "Major Sila Madd", 9, null, "images/img_0200.png"),
            q("madd2_d123a20d", "Major Sila Madd", 9, null, "images/img_0201.png"),
            q("madd2_e81e4479", "Major Sila Madd", 9, null, "images/img_0202.png"),
            q("madd2_96603acc", "Major Sila Madd", 9, null, "images/img_0203.png"),
            q("madd2_3a736efb", "Major Sila Madd", 9, null, "images/img_0204.png"),
            q("madd2_f0afc03b", "Major Sila Madd", 9, null, "images/img_0205.png"),
            q("madd2_86840b9f", "Major Sila Madd", 9, null, "images/img_0206.png"),
            q("madd2_2782c459", "Temporary Madd", 10, null, "images/img_0237.png", null, "What is the mad rule on stopping?"),
            q("madd2_eae64de5", "Temporary Madd", 10, null, "images/img_0238.png", null, "What is the mad rule on stopping?"),
            q("madd2_f12dc044", "Temporary Madd", 10, null, "images/img_0239.png", null, "What is the mad rule on stopping?"),
            q("madd2_520f8a13", "Temporary Madd", 10, null, "images/img_0240.png", null, "What is the mad rule on stopping?"),
            q("madd2_daf0b6ec", "Temporary Madd", 10, null, "images/img_0241.png", null, "What is the mad rule on stopping?"),
            q("madd2_10cb0f1d", "Temporary Madd", 10, null, "images/img_0242.png", null, "What is the mad rule on stopping?"),
            q("madd2_82835298", "Temporary Madd", 10, null, "images/img_0243.png", null, "What is the mad rule on stopping?"),
            q("madd2_881242ed", "Temporary Madd", 10, null, "images/img_0244.png", null, "What is the mad rule on stopping?"),
            q("madd2_3f925ea1", "Temporary Madd", 10, null, "images/img_0245.png", null, "What is the mad rule on stopping?"),
            q("madd2_9f3817b5", "Temporary Madd", 10, null, "images/img_0246.png", null, "What is the mad rule on stopping?"),
            q("madd2_8360bdeb", "Temporary Madd", 10, null, "images/img_0247.png", null, "What is the mad rule on stopping?"),
            q("madd2_a578ed0d", "Temporary Madd", 10, null, "images/img_0248.png", null, "What is the mad rule on stopping?"),
            q("madd2_2fb1aecf", "Temporary Madd", 10, null, "images/img_0249.png", null, "What is the mad rule on stopping?"),
            q("madd2_1650afcc", "Temporary Madd", 10, null, "images/img_0250.png", null, "What is the mad rule on stopping?"),
            q("madd2_09f0af61", "Temporary Madd", 10, null, "images/img_0251.png", null, "What is the mad rule on stopping?"),
            q("madd2_d6a19794", "Soft Madd", 11, null, "images/img_0252.png"),
            q("madd2_f7cdfce9", "Soft Madd", 11, null, "images/img_0253.png"),
            q("madd2_8e74d12c", "Soft Madd", 11, null, "images/img_0254.png"),
            q("madd2_cc3dbf05", "Soft Madd", 11, null, "images/img_0255.png"),
            q("madd2_5fae53ad", "Soft Madd", 11, null, "images/img_0256.png"),
            q("madd2_be636d12", "Soft Madd", 11, null, "images/img_0257.png"),
            q("madd2_6c8907bf", "Soft Madd", 11, null, "images/img_0258.png"),
            q("madd2_d864cfb8", "Soft Madd", 11, null, "images/img_0259.png"),
            q("madd2_dd94c3b7", "Soft Madd", 11, null, "images/img_0260.png"),
            q("madd2_24a286b3", "Soft Madd", 11, null, "images/img_0261.png"),
            q("madd2_329f0a3c", "Soft Madd", 11, null, "images/img_0262.png"),
            q("madd2_52fb0bfe", "Soft Madd", 11, null, "images/img_0263.png"),
            q("madd2_1ca52bb6", "Soft Madd", 11, null, "images/img_0264.png"),
            q("madd2_78cb9486", "Soft Madd", 11, null, "images/img_0265.png"),
            q("madd_tabii_1", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_1.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_2", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_2.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_3", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_3.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_4", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_4.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_5", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_5.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_6", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_6.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_7", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_7.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_8", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_8.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_9", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_9.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_10", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_10.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_11", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_11.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_12", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_12.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_13", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_13.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_14", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_14.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_15", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_15.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_16", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_16.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_17", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_17.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_18", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_18.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_19", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_19.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_20", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_20.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_21", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_21.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_22", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_22.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_23", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_23.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_24", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_24.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_25", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_25.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_26", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_26.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_27", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_27.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_31", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_31.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_34", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_34.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_tabii_38", "Natural Madd", 12, "Natural Madd", "images/madd_tabii_Screenshot_38.png", ["Natural Madd","Substitute","Connected","Separated"], "What is the Madd rule in this word?"),
            q("madd_kalimi_muth_1", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_1.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_2", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_2.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_3", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_3.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_4", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_4.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_5", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_5.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_6", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_6.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_7", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_7.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_8", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_8.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_9", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_9.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_10", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_10.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_11", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_11.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_12", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_12.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_13", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_13.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_muth_14", "Permanent Word Based Heavy", 13, "Permanent Word Based Heavy", "images/madd_kalimi_muthaqqal_Screenshot_14.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_mukh_1", "Permanent Word Based Light", 14, "Permanent Word Based Light", "images/madd_kalimi_mukhaffaf_Screenshot_1.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_kalimi_mukh_14", "Permanent Word Based Light", 14, "Permanent Word Based Light", "images/madd_kalimi_mukhaffaf_Screenshot_14.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule?"),
            q("madd_harfi_40_lam", "Permanent Letter Based Heavy", 15, "Permanent Letter Based Heavy", "images/madd_harfi_Screenshot_40.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (اللام / Lām)?"),
            q("madd_harfi_40_meem", "Permanent Letter Based Light", 16, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_40.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الميم / Meem)?"),
            q("madd_harfi_1_lam", "Permanent Letter Based Heavy", 15, "Permanent Letter Based Heavy", "images/madd_harfi_Screenshot_1.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (اللام / Lām)?"),
            q("madd_harfi_1_meem", "Permanent Letter Based Light", 16, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_1.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الميم / Meem)?"),
            q("madd_harfi_1_saad", "Permanent Letter Based Light", 17, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_1.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الصاد / Sād)?"),
            q("madd_harfi_2_lam", "Permanent Letter Based Light", "Letter Lām (لاَمْ) is spelled with 3 letters whose middle is Madd and ending Saakin Meem is NOT merged with Idgham → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).", "Permanent Letter Based Light", "images/madd_harfi_Screenshot_2.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (اللام / Lām)?"),
            q("madd_harfi_4_kaf", "Permanent Letter Based Light", "Letter Kāf (كَافْ) is spelled with 3 letters whose middle is Madd and ending Saakin Faa is NOT merged (no Idgham) → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).", "Permanent Letter Based Light", "images/madd_harfi_Screenshot_4.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الكاف / Kāf)?"),
            q("madd_harfi_4_saad", "Permanent Letter Based Light", 17, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_4.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الصاد / Sād)?"),
            q("madd_harfi_5_lam", "Permanent Letter Based Heavy", 15, "Permanent Letter Based Heavy", "images/madd_harfi_Screenshot_5.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (اللام / Lām)?"),
            q("madd_harfi_5_meem", "Permanent Letter Based Light", 16, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_5.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الميم / Meem)?"),
            q("madd_harfi_6_seen", "Permanent Letter Based Heavy", "Letter Seen (سِينْ) is spelled with 3 letters whose middle is Madd and ending Saakin Noon is merged (Idgham) into the following Meem → Compulsory Letter-Based Heavy (Madd Lazim Harfi Muthaqqal, 6 counts).", "Permanent Letter Based Heavy", "images/madd_harfi_Screenshot_6.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (السين / Seen)?"),
            q("madd_harfi_6_meem", "Permanent Letter Based Light", 16, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_6.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الميم / Meem)?"),
            q("madd_harfi_7_seen", "Permanent Letter Based Light", 18, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_7.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (السين / Seen)?"),
            q("madd_harfi_8_seen", "Permanent Letter Based Light", 18, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_8.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (السين / Seen)?"),
            q("madd_harfi_9_meem", "Permanent Letter Based Light", 16, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_9.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الميم / Meem)?"),
            q("madd_harfi_9_seen", "Permanent Letter Based Light", 18, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_9.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (السين / Seen)?"),
            q("madd_harfi_9_qaf", "Permanent Letter Based Light", 19, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_9.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (القاف / Qāf)?"),
            q("madd_harfi_10_saad", "Permanent Letter Based Light", 17, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_10.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الصاد / Sād)?"),
            q("madd_harfi_11_meem", "Permanent Letter Based Light", 16, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_11.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (الميم / Meem)?"),
            q("madd_harfi_12_qaf", "Permanent Letter Based Light", 19, "Permanent Letter Based Light", "images/madd_harfi_Screenshot_12.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (القاف / Qāf)?"),
            q("madd_harfi_13_noon", "Permanent Letter Based Light", "Letter Noon (نُونْ) is spelled with 3 letters whose middle is Madd and ending Saakin Noon is NOT merged (no Idgham) → Compulsory Letter-Based Light (Madd Lazim Harfi Mukhaffaf, 6 counts).", "Permanent Letter Based Light", "images/madd_harfi_Screenshot_13.png", ["Permanent Word Based Heavy","Permanent Word Based Light","Permanent Letter Based Heavy","Permanent Letter Based Light"], "What is the Madd Lazim rule for letter (النون / Noon)?")
        ]),
        "qalqalah": defCat("Qalqalah", ["Qalqalah","No Qalqalah"], "Is there Qalqalah in this example?", [
            q("qalqalah_gen_1", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_1.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_2", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_2.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_3", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_3.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_4", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_4.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_5", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_5.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_6", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_6.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_7", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_7.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_8", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_8.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_9", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_9.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_10", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_10.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_11", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_11.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_12", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_12.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_13", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_13.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_14", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_14.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_15", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_15.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_16", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_16.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_17", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_17.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_18", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_18.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_19", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_19.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_20", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_20.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_21", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_21.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_22", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_22.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_24", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_24.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_25", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_new_Screenshot_25.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_ashadd", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_ashadd.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_alhaqq", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_alhaqq.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_watabb", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_watabb.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_alhajj", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_alhajj.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_muheet", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_muheet.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_ahad", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_ahad.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_alfalaq", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_alfalaq.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_waqab", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_waqab.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_gen_ukhrij", "Qalqalah", 20, "General Qalqalah", "images/qalqalah_ukhrij.png", ["Qalqalah","No Qalqalah"]),
            q("qalqalah_deg_1", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_1.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_2", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_2.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_3", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_3.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_4", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_4.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_5", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_5.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_6", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_6.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_7", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_7.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_8", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_8.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_9", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_9.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_10", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_10.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_11", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_11.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_12", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_12.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_13", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_13.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_14", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_14.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_15", "Minor", 21, "Qalqalah Degree", "images/qalqalah_new_Screenshot_15.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_16", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_16.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_17", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_17.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_18", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_18.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_19", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_19.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_20", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_20.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_21", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_21.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_22", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_22.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_24", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_24.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_25", "Medium", 22, "Qalqalah Degree", "images/qalqalah_new_Screenshot_25.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_ashadd", "Major", 23, "Qalqalah Degree", "images/qalqalah_ashadd.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_alhaqq", "Major", 23, "Qalqalah Degree", "images/qalqalah_alhaqq.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_watabb", "Major", 23, "Qalqalah Degree", "images/qalqalah_watabb.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_alhajj", "Major", 23, "Qalqalah Degree", "images/qalqalah_alhajj.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_muheet", "Medium", 22, "Qalqalah Degree", "images/qalqalah_muheet.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_ahad", "Medium", 22, "Qalqalah Degree", "images/qalqalah_ahad.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_alfalaq", "Medium", 22, "Qalqalah Degree", "images/qalqalah_alfalaq.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_waqab", "Medium", 22, "Qalqalah Degree", "images/qalqalah_waqab.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?"),
            q("qalqalah_deg_ukhrij", "Medium", 22, "Qalqalah Degree", "images/qalqalah_ukhrij.png", ["Minor","Medium","Major"], "What is the degree of Qalqalah?")
        ]),
        "noon_sakinah_tanween": defCat("Noon Sakinah & Tanween", ["Izhar","Idgham with Ghunnah","Idgham without Ghunnah","Iqlab","Ikhfa","Izhar Mutlaq"], "What is the rule?", [
            q("mutlaq_1", "Izhar Mutlaq", 24, "Izhar Mutlaq", null, null, "What is the ruling of the Noon Saakinah?"),
            q("mutlaq_2", "Izhar Mutlaq", 25, "Izhar Mutlaq", null, null, "What is the ruling of the Noon Saakinah?"),
            q("mutlaq_3", "Izhar Mutlaq", 25, "Izhar Mutlaq", null, null, "What is the ruling of the Noon Saakinah?"),
            q("mutlaq_4", "Izhar Mutlaq", 24, "Izhar Mutlaq", null, null, "What is the ruling of the Noon Saakinah?"),
            q("tanween_ikhfaa_Screenshot_1", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_10", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_11", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_12", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_13", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_14", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_15", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_16", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_2", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_3", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_4", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_5", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_6", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_7", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_8", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("tanween_ikhfaa_Screenshot_9", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_1", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_10", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_2", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_3", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_4", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_5", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_6", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_7", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_8", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_ikhfaa_Screenshot_9", "Ikhfa", 26, "Ikhfa", null, null, "What is the Tajweed rule here?"),
            q("noon_1", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0001.png"),
            q("noon_2", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0002.png"),
            q("noon_3", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0003.png"),
            q("noon_4", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0004.png"),
            q("noon_5", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0005.png"),
            q("noon_6", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0006.png"),
            q("noon_7", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0007.png"),
            q("noon_8", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0008.png"),
            q("noon_9", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0009.png"),
            q("noon_10", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0010.png"),
            q("noon_11", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0011.png"),
            q("noon_12", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0012.png"),
            q("noon_13", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0013.png"),
            q("noon_14", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0014.png"),
            q("noon_15", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0015.png"),
            q("noon_16", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0016.png"),
            q("noon_17", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0017.png"),
            q("noon_18", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0018.png"),
            q("noon_19", "Izhar", 29, "Izhar", "images/img_0019.png"),
            q("noon_20", "Izhar", 29, "Izhar", "images/img_0020.png"),
            q("noon_21", "Izhar", 29, "Izhar", "images/img_0021.png"),
            q("noon_22", "Izhar", 29, "Izhar", "images/img_0022.png"),
            q("noon_23", "Izhar", 29, "Izhar", "images/img_0023.png"),
            q("noon_24", "Izhar", 29, "Izhar", "images/img_0024.png"),
            q("noon_25", "Izhar", 29, "Izhar", "images/img_0025.png"),
            q("noon_26", "Izhar", 29, "Izhar", "images/img_0026.png"),
            q("noon_27", "Izhar", 29, "Izhar", "images/img_0027.png"),
            q("noon_28", "Izhar", 29, "Izhar", "images/img_0028.png"),
            q("noon_29", "Izhar", 29, "Izhar", "images/img_0029.png"),
            q("noon_30", "Izhar", 29, "Izhar", "images/img_0030.png"),
            q("noon_31", "Izhar", 29, "Izhar", "images/img_0031.png"),
            q("noon_32", "Izhar", 29, "Izhar", "images/img_0032.png"),
            q("noon_33", "Izhar", 29, "Izhar", "images/img_0033.png"),
            q("noon_34", "Izhar", 29, "Izhar", "images/img_0034.png"),
            q("noon_35", "Izhar", 29, "Izhar", "images/img_0035.png"),
            q("noon_36", "Izhar", 29, "Izhar", "images/img_0036.png"),
            q("noon_37", "Izhar", 29, "Izhar", "images/img_0037.png"),
            q("noon_38", "Izhar", 29, "Izhar", "images/img_0038.png"),
            q("noon_39", "Izhar", 29, "Izhar", "images/img_0039.png"),
            q("noon_40", "Izhar", 29, "Izhar", "images/img_0040.png"),
            q("noon_41", "Izhar", 29, "Izhar", "images/img_0041.png"),
            q("noon_42", "Izhar", 29, "Izhar", "images/img_0042.png"),
            q("noon_43", "Izhar", 29, "Izhar", "images/img_0043.png"),
            q("noon_44", "Izhar", 29, "Izhar", "images/img_0044.png"),
            q("noon_45", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0045.png"),
            q("noon_46", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0046.png"),
            q("noon_47", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0047.png"),
            q("noon_48", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0048.png"),
            q("noon_49", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0049.png"),
            q("noon_50", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0050.png"),
            q("noon_51", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0051.png"),
            q("noon_52", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0052.png"),
            q("noon_53", "Idgham without Ghunnah", 28, "Idgham without Ghunnah", "images/img_0053.png"),
            q("noon_54", "Iqlab", 30, "Iqlab", "images/img_0054.png"),
            q("noon_55", "Iqlab", 30, "Iqlab", "images/img_0055.png"),
            q("noon_56", "Iqlab", 30, "Iqlab", "images/img_0056.png"),
            q("noon_57", "Iqlab", 30, "Iqlab", "images/img_0057.png"),
            q("noon_58", "Iqlab", 30, "Iqlab", "images/img_0058.png"),
            q("noon_59", "Iqlab", 30, "Iqlab", "images/img_0059.png"),
            q("noon_60", "Iqlab", 30, "Iqlab", "images/img_0060.png"),
            q("noon_61", "Iqlab", 30, "Iqlab", "images/img_0061.png"),
            q("noon_62", "Iqlab", 30, "Iqlab", "images/img_0062.png"),
            q("noon_63", "Iqlab", 30, "Iqlab", "images/img_0063.png"),
            q("noon_64", "Iqlab", 30, "Iqlab", "images/img_0064.png"),
            q("noon_65", "Iqlab", 30, "Iqlab", "images/img_0065.png"),
            q("noon_66", "Iqlab", 30, "Iqlab", "images/img_0066.png"),
            q("noon_67", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0067.png"),
            q("noon_68", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0068.png"),
            q("noon_69", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0069.png"),
            q("noon_70", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0070.png"),
            q("noon_71", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0071.png"),
            q("noon_72", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0072.png"),
            q("noon_73", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0073.png"),
            q("noon_74", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0074.png"),
            q("noon_75", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0075.png"),
            q("noon_76", "Idgham with Ghunnah", 27, "Idgham with Ghunnah", "images/img_0076.png"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_1", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_1.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_10", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_10.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_11", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_11.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_12", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_12.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_13", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_13.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_14", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_14.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_15", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_15.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_16", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_16.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_2", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_2.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_3", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_3.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_4", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_4.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_5", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_5.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_6", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_6.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_7", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_7.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_8", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_8.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_tanween_ikhfaa_Screenshot_9", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/tanween_ikhfaa_Screenshot_9.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_1", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_1.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_10", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_10.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_2", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_2.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_3", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_3.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_4", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_4.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_5", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_5.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_6", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_6.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_7", "Light Ghunnah", 32, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_7.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_8", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_8.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("ikhfa_gh_noon_ikhfaa_Screenshot_9", "Heavy Ghunnah", 31, "Ikhfa Ghunnah", "images/noon_ikhfaa_Screenshot_9.png", ["Heavy Ghunnah","Light Ghunnah"], "Is the Ghunnah of Ikhfa heavy or light?"),
            q("idgham_comp_noon_1", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0001.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_2", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0002.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_3", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0003.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_4", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0004.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_5", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0005.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_6", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0006.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_7", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0007.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_8", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0008.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_9", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0009.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_10", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0010.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_11", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0011.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_12", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0012.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_13", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0013.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_14", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0014.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_15", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0015.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_16", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0016.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_17", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0017.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_18", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0018.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_45", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0045.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_46", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0046.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_47", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0047.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_48", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0048.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_49", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0049.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_50", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0050.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_51", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0051.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_52", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0052.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_53", "Complete Idgham (Kamil)", 35, "Idgham Completeness", "images/img_0053.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_67", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0067.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_68", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0068.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_69", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0069.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_70", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0070.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_71", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0071.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_72", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0072.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_73", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0073.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_74", "Incomplete Idgham (Naqis)", 33, "Idgham Completeness", "images/img_0074.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_75", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0075.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?"),
            q("idgham_comp_noon_76", "Complete Idgham (Kamil)", 34, "Idgham Completeness", "images/img_0076.png", ["Complete Idgham (Kamil)","Incomplete Idgham (Naqis)"], "What is the type of Idgham (Complete or Incomplete)?")
        ]),
        "meem_sakinah": defCat("Meem Sakinah", ["Oral + Hiding","Oral + Merger","Oral + Clarity"], "What is the rule?", [
            q("meem_77", "Oral + Clarity", 36, null, "images/img_0077.png"),
            q("meem_78", "Oral + Clarity", 36, null, "images/img_0078.png"),
            q("meem_79", "Oral + Clarity", 36, null, "images/img_0079.png"),
            q("meem_80", "Oral + Clarity", 36, null, "images/img_0080.png"),
            q("meem_81", "Oral + Clarity", 36, null, "images/img_0081.png"),
            q("meem_82", "Oral + Clarity", 36, null, "images/img_0082.png"),
            q("meem_83", "Oral + Merger", 37, null, "images/img_0083.png"),
            q("meem_84", "Oral + Merger", 37, null, "images/img_0084.png"),
            q("meem_85", "Oral + Merger", 37, null, "images/img_0085.png"),
            q("meem_86", "Oral + Merger", 37, null, "images/img_0086.png"),
            q("meem_87", "Oral + Merger", 37, null, "images/img_0087.png"),
            q("meem_88", "Oral + Merger", 37, null, "images/img_0088.png"),
            q("meem_89", "Oral + Merger", 37, null, "images/img_0089.png"),
            q("meem_90", "Oral + Merger", 37, null, "images/img_0090.png"),
            q("meem_91", "Oral + Hiding", 38, null, "images/img_0091.png"),
            q("meem_92", "Oral + Hiding", 38, null, "images/img_0092.png"),
            q("meem_93", "Oral + Hiding", 38, null, "images/img_0093.png"),
            q("meem_94", "Oral + Hiding", 38, null, "images/img_0094.png"),
            q("meem_95", "Oral + Hiding", 38, null, "images/img_0095.png"),
            q("meem_96", "Oral + Hiding", 38, null, "images/img_0096.png"),
            q("meem_97", "Oral + Hiding", 38, null, "images/img_0097.png"),
            q("meem_98", "Oral + Hiding", 38, null, "images/img_0098.png"),
            q("meem_99", "Oral + Hiding", 38, null, "images/img_0099.png"),
            q("meem_100", "Oral + Hiding", 38, null, "images/img_0100.png"),
            q("meem_101", "Oral + Hiding", 38, null, "images/img_0101.png"),
            q("meem_102", "Oral + Hiding", 38, null, "images/img_0102.png"),
            q("meem_103", "Oral + Merger", 37, null, "images/img_0103.png"),
            q("meem_104", "Oral + Merger", 37, null, "images/img_0104.png"),
            q("meem_105", "Oral + Clarity", 36, null, "images/img_0105.png"),
            q("meem_106", "Oral + Hiding", 38, null, "images/img_0106.png"),
            q("meem_107", "Oral + Hiding", 38, null, "images/img_0107.png"),
            q("meem_108", "Oral + Clarity", 36, null, "images/img_0108.png")
        ]),
        "madd": defCat("Al-Modood", ["Muttasil","Munfasil","Badal"], null, [
        ]),
        "image_bank": defCat("Noon and Meem Mushaddad", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of meem with shadda?", [
            q("mush_109", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0109.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_110", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0110.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_111", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0111.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_112", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0112.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_113", "Two counts of ghunna", 39, "Noon Mushaddad", "images/img_0113.png", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of noon with shadda?"),
            q("mush_114", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0114.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_115", "Two counts of ghunna", 39, "Noon Mushaddad", "images/img_0115.png", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of noon with shadda?"),
            q("mush_116", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0116.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_117", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0117.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_118", "Two counts of ghunna", 39, "Noon Mushaddad", "images/img_0118.png", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of noon with shadda?"),
            q("mush_119", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0119.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_120", "Two counts of ghunna", 39, "Noon Mushaddad", "images/img_0120.png", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of noon with shadda?"),
            q("mush_121", "Two counts of ghunna", 39, "Noon Mushaddad", "images/img_0121.png", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of noon with shadda?"),
            q("mush_122", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0122.png", ["Two counts of ghunna","Four counts of ghunna"]),
            q("mush_123", "Two counts of ghunna", 39, "Noon Mushaddad", "images/img_0123.png", ["Two counts of ghunna","Four counts of ghunna"], "What is the rule of noon with shadda?"),
            q("mush_124", "Two counts of ghunna", 39, "Meem Mushaddad", "images/img_0124.png", ["Two counts of ghunna","Four counts of ghunna"])
        ]),
        "tafkheem_tarqeeq": defCat("Tafkheem & Tarqeeq", ["Heavy Raa","Light Raa","Heavy Letter","Light Letter","Heavy Laam","Light Laam","Heavy Alif","Light Alif"], "What is the rule of letter Raa?", [
            q("tafkheem_55392553", "Light Raa", 40, "Light Ra", "images/img_0269.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_87cf9eae", "Light Raa", 40, "Light Ra", "images/img_0270.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_53c4ce0d", "Light Raa", 40, "Light Ra", "images/img_0271.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_63ddface", "Light Raa", 40, "Light Ra", "images/img_0272.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_88baf0ce", "Light Raa", 40, "Light Ra", "images/img_0273.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_22f6fd3a", "Light Raa", 40, "Light Ra", "images/img_0274.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_f364fda1", "Light Raa", 40, "Light Ra", "images/img_0275.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_55ea0fcf", "Light Raa", 40, "Light Ra", "images/img_0276.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_9876c672", "Light Raa", 40, "Light Ra", "images/img_0277.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_93ed953f", "Light Raa", 40, "Light Ra", "images/img_0278.png", ["Light Raa","Heavy Raa"]),
            q("tafkheem_eba30059", "Heavy Letter", 41, "Always Heavy", "images/img_0279.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_06fd5475", "Heavy Letter", 41, "Always Heavy", "images/img_0280.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_506d1b33", "Heavy Letter", 41, "Always Heavy", "images/img_0281.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_1f515ffe", "Heavy Letter", 41, "Always Heavy", "images/img_0282.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_0d9b786c", "Heavy Letter", 41, "Always Heavy", "images/img_0283.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_84292953", "Heavy Letter", 41, "Always Heavy", "images/img_0284.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_eb626fef", "Heavy Letter", 41, "Always Heavy", "images/img_0285.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_0076f726", "Heavy Letter", 41, "Always Heavy", "images/img_0286.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_619c3242", "Heavy Letter", 41, "Always Heavy", "images/img_0287.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_ed7ac59a", "Heavy Letter", 41, "Always Heavy", "images/img_0288.png", ["Heavy Letter","Light Letter"], "What is the rule of the highlighted letter?"),
            q("tafkheem_9541b76a", "Light Alif", 42, "Alif", "images/img_0289.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_8ceb5143", "Heavy Alif", 43, "Alif", "images/img_0290.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_862a8d2e", "Light Alif", 42, "Alif", "images/img_0291.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_0cd4d1e6", "Heavy Alif", 43, "Alif", "images/img_0292.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_559e1704", "Heavy Alif", 43, "Alif", "images/img_0293.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_681f5d64", "Light Alif", 42, "Alif", "images/img_0294.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_2479bae5", "Heavy Alif", 43, "Alif", "images/img_0295.png", ["Heavy Alif","Light Alif"], "What is the rule of letter Alef?"),
            q("tafkheem_9b84a614", "Heavy Raa", 44, "Heavy Ra", "images/img_0296.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_fd7d0652", "Heavy Raa", 44, "Heavy Ra", "images/img_0297.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_047296b8", "Heavy Raa", 44, "Heavy Ra", "images/img_0298.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_4426f2e9", "Heavy Raa", 44, "Heavy Ra", "images/img_0299.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_ddfd13dc", "Heavy Raa", 44, "Heavy Ra", "images/img_0300.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_65df88e3", "Heavy Raa", 44, "Heavy Ra", "images/img_0301.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_c59c42af", "Heavy Raa", 44, "Heavy Ra", "images/img_0302.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_5e00b62b", "Heavy Raa", 44, "Heavy Ra", "images/img_0303.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_03ced931", "Heavy Raa", 44, "Heavy Ra", "images/img_0304.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_89c9bc76", "Heavy Raa", 44, "Heavy Ra", "images/img_0305.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_d6928aad", "Heavy Raa", 44, "Heavy Ra", "images/img_0306.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_38cdcc35", "Heavy Raa", 44, "Heavy Ra", "images/img_0307.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_804a69ff", "Heavy Raa", 44, "Heavy Ra", "images/img_0308.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_8789c072", "Heavy Raa", 44, "Heavy Ra", "images/img_0309.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_b6763703", "Heavy Raa", 44, "Heavy Ra", "images/img_0310.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_ad6cb66c", "Heavy Raa", 44, "Heavy Ra", "images/img_0311.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_ee8aff9c", "Heavy Raa", 44, "Heavy Ra", "images/img_0312.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_9b036da6", "Heavy Raa", 44, "Heavy Ra", "images/img_0313.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_12cd51d3", "Heavy Raa", 44, "Heavy Ra", "images/img_0314.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_50d5ccd1", "Heavy Raa", 44, "Heavy Ra", "images/img_0315.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_039363b4", "Heavy Raa", 44, "Heavy Ra", "images/img_0316.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_7a3ec117", "Heavy Raa", 44, "Heavy Ra", "images/img_0317.png", ["Heavy Raa","Light Raa"]),
            q("tafkheem_aa5030db", "Both are permissible — Tarqeeq is preferred when stopping.", 45, "Ra Both Options", "images/img_0318.png", ["Both are permissible — Tarqeeq is preferred when stopping.","Both are permissible — Tafkheem is preferred when stopping.","Light Raa","Heavy Raa"]),
            q("tafkheem_7874357b", "Both are permissible — Tarqeeq is preferred when stopping.", 45, "Ra Both Options", "images/img_0319.png", ["Both are permissible — Tarqeeq is preferred when stopping.","Both are permissible — Tafkheem is preferred when stopping.","Light Raa","Heavy Raa"]),
            q("tafkheem_fafd0261", "Both are permissible — Tarqeeq is preferred when stopping.", 45, "Ra Both Options", "images/img_0320.png", ["Both are permissible — Tarqeeq is preferred when stopping.","Both are permissible — Tafkheem is preferred when stopping.","Light Raa","Heavy Raa"]),
            q("tafkheem_7de9b63e", "Both are permissible — Tarqeeq is preferred when stopping.", 45, "Ra Both Options", "images/img_0321.png", ["Both are permissible — Tarqeeq is preferred when stopping.","Both are permissible — Tafkheem is preferred when stopping.","Light Raa","Heavy Raa"]),
            q("tafkheem_326d92c5", "Both are permissible — Tarqeeq is preferred when stopping.", 45, "Ra Both Options", "images/img_0322.png", ["Both are permissible — Tarqeeq is preferred when stopping.","Both are permissible — Tafkheem is preferred when stopping.","Light Raa","Heavy Raa"]),
            q("tafkheem_efe337bb", "Both are permissible — Tafkheem is preferred when stopping.", "Raa with Sukoon when stopping preceded by Fathah/Dammah or Isti'la letter → Both permissible, Heavy (Tafkheem) is preferred.", "Ra Both Options", "images/img_0323.png", ["Both are permissible — Tafkheem is preferred when stopping.","Both are permissible — Tarqeeq is preferred when stopping.","Heavy Raa","Light Raa"]),
            q("tafkheem_28e3f87a", "Heavy Laam", 46, "Lam of Allah", "images/img_0268.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_1", "Heavy Laam", 46, "Lam of Allah", "images/lam_allah_new_Screenshot_1.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_2", "Heavy Laam", 46, "Lam of Allah", "images/lam_allah_new_Screenshot_2.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_3", "Heavy Laam", 46, "Lam of Allah", "images/lam_allah_new_Screenshot_3.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_4", "Heavy Laam", 46, "Lam of Allah", "images/lam_allah_new_Screenshot_4.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_5", "Heavy Laam", 46, "Lam of Allah", "images/lam_allah_new_Screenshot_5.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_6", "Light Laam", 47, "Lam of Allah", "images/lam_allah_new_Screenshot_6.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_7", "Light Laam", 47, "Lam of Allah", "images/lam_allah_new_Screenshot_7.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_8", "Light Laam", 47, "Lam of Allah", "images/lam_allah_new_Screenshot_8.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_9", "Heavy Laam", 46, "Lam of Allah", "images/lam_allah_new_Screenshot_9.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_10", "Light Laam", 47, "Lam of Allah", "images/lam_allah_new_Screenshot_10.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_11", "Light Laam", 47, "Lam of Allah", "images/lam_allah_new_Screenshot_11.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?"),
            q("lam_allah_12", "Light Laam", 47, "Lam of Allah", "images/lam_allah_new_Screenshot_12.png", ["Heavy Laam","Light Laam"], "What is the rule of letter Laam?")
        ]),
        "hamzat_wasl": defCat("Hamzat Al-Wasl", ["Dropped","Start with damma","Start with fatha","Start with kasra"], "What is the rule for Hamzat Al-Wasl?", [
            q("hamzat_wasl_dropped_Screenshot_1", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_2", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_3", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_4", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_5", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_6", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_7", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_8", "Dropped", 48),
            q("hamzat_wasl_dropped_Screenshot_9", "Dropped", 48),
            q("hamzat_wasl_damma_Screenshot_1", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_14", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_2", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_3", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_4", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_5", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_6", "Start with damma", 49),
            q("hamzat_wasl_damma_Screenshot_7", "Start with damma", 49),
            q("hamzat_wasl_fatha_Screenshot_1", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_2", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_3", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_4", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_5", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_6", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_7", "Start with fatha", 50),
            q("hamzat_wasl_fatha_Screenshot_8", "Start with fatha", 50),
            q("hamzat_wasl_kasra_Screenshot_1", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_10", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_11", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_12", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_13", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_2", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_3", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_4", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_5", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_6", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_7", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_8", "Start with kasra", 51),
            q("hamzat_wasl_kasra_Screenshot_9", "Start with kasra", 51)
        ]),
        "makharij": defCat("Makharij", ["Jawf","Halq","Lisan","Shafatain","Khaishum"], null, [
        ]),
        "sifaat": defCat("Sifaat", ["Hams","Jahr","Shiddah","Rakhawah","Tawassut"], null, [
        ]),
        "lam_shamsiyyah_qamariyyah": defCat("Lam Shamsiyyah & Qamariyyah", ["Lam Qamariyyah","Lam Shamsiyyah"], "What is the rule of Lam?", [
            q("lam_qam_1", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_1.png"),
            q("lam_qam_2", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_2.png"),
            q("lam_qam_3", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_3.png"),
            q("lam_qam_4", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_4.png"),
            q("lam_qam_5", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_5.png"),
            q("lam_qam_6", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_6.png"),
            q("lam_qam_7", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_7.png"),
            q("lam_qam_18", "Lam Qamariyyah", 52, null, "images/lam_qamariyyah_Screenshot_18.png"),
            q("lam_sham_1", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_1.png"),
            q("lam_sham_2", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_2.png"),
            q("lam_sham_3", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_3.png"),
            q("lam_sham_4", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_4.png"),
            q("lam_sham_5", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_5.png"),
            q("lam_sham_6", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_6.png"),
            q("lam_sham_7", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_7.png"),
            q("lam_sham_8", "Lam Shamsiyyah", 53, null, "images/lam_shamsiyyah_Screenshot_8.png")
        ]),
        "lam_harf": defCat("Lam of Hal & Bal", ["Idgham (Merging)","Izhar (Clarity)"], "What is the rule of the Saakin Lam in Hal / Bal?", [
            q("lam_harf_1", "Idgham (Merging)", 54, "Idgham", "images/lam_harf_bal_rafaahu.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_2", "Idgham (Merging)", 54, "Idgham", "images/lam_harf_bal_rabbukum.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_3", "Idgham (Merging)", 55, "Idgham", "images/lam_harf_bal_laa_takhafoo.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_4", "Idgham (Merging)", 55, "Idgham", "images/lam_harf_bal_laa_yuminoon.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_5", "Idgham (Merging)", 55, "Idgham", "images/lam_harf_bal_lammaa.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_6", "Idgham (Merging)", 56, "Idgham", "images/lam_harf_hal_lakum.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_7", "Idgham (Merging)", 56, "Idgham", "images/lam_harf_hal_laka.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_8", "Idgham (Merging)", 55, "Idgham", "images/lam_harf_bal_lajjoo.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_9", "Izhar (Clarity)", "The Lam of \"Hal\" is pronounced clearly (Izhar) before the Hamzah.", "Izhar", "images/lam_harf_hal_ataaka.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_10", "Izhar (Clarity)", "The Lam of \"Hal\" is pronounced clearly (Izhar) before the letter Taa.", "Izhar", "images/lam_harf_hal_taraa.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_11", "Izhar (Clarity)", "The Lam of \"Hal\" is pronounced clearly (Izhar) before the letter Thaa.", "Izhar", "images/lam_harf_hal_thuwwiba.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_12", "Izhar (Clarity)", "The Lam of \"Hal\" is pronounced clearly (Izhar) before the letter Yaa.", "Izhar", "images/lam_harf_hal_yastawi.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_13", "Izhar (Clarity)", "The Lam of \"Hal\" is pronounced clearly (Izhar) before the letter Noon.", "Izhar", "images/lam_harf_hal_nunabbiukum.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_14", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Haa.", "Izhar", "images/lam_harf_bal_hum.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_15", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Faa.", "Izhar", "images/lam_harf_bal_faalahu.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_16", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Taa.", "Izhar", "images/lam_harf_bal_tabaa.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_17", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Seen.", "Izhar", "images/lam_harf_bal_sawwalat.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_18", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Zhaa.", "Izhar", "images/lam_harf_bal_zanantum.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_19", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Kaaf.", "Izhar", "images/lam_harf_bal_kazzaboo.png", ["Idgham (Merging)","Izhar (Clarity)"]),
            q("lam_harf_20", "Izhar (Clarity)", "The Lam of \"Bal\" is pronounced clearly (Izhar) before the letter Jeem.", "Izhar", "images/lam_harf_bal_jaaahum.png", ["Idgham (Merging)","Izhar (Clarity)"])
        ])
    };

    window.TAJWEED_BANK = TAJWEED_BANK;
})(typeof globalThis !== "undefined" ? globalThis : (typeof window !== "undefined" ? window : this));
